version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:
  nginx:
    << : *default-opts
    image: nginx:1.19.2
    environment:
      SIMVA_DNS_SERVICE_IP: ${SIMVA_DNS_SERVICE_IP:-172.30.0.53}
      SIMVA_LOAD_BALANCER_IP: ${SIMVA_LOAD_BALANCER_IP:-172.30.0.80}
      SIMVA_INTERNAL_DOMAIN: ${SIMVA_INTERNAL_DOMAIN:-internal.test}
      SIMVA_EXTERNAL_DOMAIN: ${SIMVA_EXTERNAL_DOMAIN:-external.test}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${SIMVA_CONFIG_HOME:-/home/vagrant/docker-stacks/config}/traefik/nginx/templates:/etc/nginx/templates:ro"
      - "${SIMVA_TLS_HOME:?TLS home folder required}:/etc/traefik/ssl:ro"
    depends_on:
      - traefik
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    restart: unless-stopped
    hostname: "nginx.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
    dns:
      - ${SIMVA_DNS_SERVICE_IP:-172.30.0.53}
    networks:
      default:
        aliases:
          - "nginx.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
      traefik_services:
        ipv4_address: "${SIMVA_LOAD_BALANCER_IP:-172.30.0.80}"
        aliases:
          - "nginx.${SIMVA_INTERNAL_DOMAIN:-internal.test}"

  whoami:
    << : *default-opts
    image: containous/whoami
    volumes:
      - /etc/localtime:/etc/localtime:ro
    hostname: "whoami.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
    dns:
      - ${SIMVA_DNS_SERVICE_IP:-172.30.0.53}
    networks:
      default:
        aliases:
          - "whoami.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
      traefik_services:
        aliases:
          - "whoami.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"