version: '3.7'

services:
  whoami:
    image: containous/whoami
    hostname: "whoami.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
    dns:
      - ${SIMVA_DNS_SERVICE_IP:-172.30.0.53}
    networks:
      default:
        aliases:
          - "whoami.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
      traefik_services:
        aliases:
          - "whoami.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"

  traefik:
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host