version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  traefik_services:
    name: "${SIMVA_SERVICE_NETWORK:-traefik_services}"
    external: true

services:
  mariadb:
    << : *default-opts
    image: ${SIMVA_MARIADB_IMAGE:-mariadb}:${SIMVA_MARIADB_VERSION:-10.4.13}
    volumes:
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/keycloak/mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${SIMVA_KEYCLOAK_MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${SIMVA_KEYCLOAK_MYSQL_DATABASE:-keycloak}
      - MYSQL_USER=${SIMVA_KEYCLOAK_MYSQL_USER:-keycloak}
      - MYSQL_PASSWORD=${SIMVA_KEYCLOAK_MYSQL_PASSWORD:-password}
# https://github.com/docker-library/mariadb/issues/261
# https://github.com/docker-library/mariadb/issues/262
      - MYSQL_INITDB_SKIP_TZINFO=true
    healthcheck:
      test: "mysqladmin ping -h localhost -u root -p${SIMVA_KEYCLOAK_MYSQL_ROOT_PASSWORD:-root} --silent"
      interval: 60s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    hostname: mariadb.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - mariadb.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}

  mariadb-backup:
    << : *default-opts
    image: ${SIMVA_MARIADB_IMAGE:-mariadb}:${SIMVA_MARIADB_VERSION:-10.4.13}
    volumes:
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/keycloak/mariadb-dump:/dump
      - /etc/localtime:/etc/localtime:ro
      - ${SIMVA_CONTAINER_TOOLS_HOME:-/home/vagrant/docker-stacks/container-tools}:/container-tools
    environment:
      - MYSQL_HOST=mariadb.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      - MYSQL_ROOT_PASSWORD=${SIMVA_KEYCLOAK_MYSQL_ROOT_PASSWORD:-root}
      - BACKUP_NUM_KEEP=7
      - BACKUP_FREQUENCY=1d
      - WAIT_TIMEOUT=${SIMVA_WAIT_TIMEOUT:-240}
    entrypoint: |
      bash -c '/container-tools/wait-for-it.sh -h $${MYSQL_HOST} -p 3306 -t $${WAIT_TIMEOUT} -- bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        mysqldump --all-databases -h"$$MYSQL_HOST" -uroot -p"$$MYSQL_ROOT_PASSWORD" > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql
        (ls -t /dump/dump*.sql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.sql)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    restart: unless-stopped
    hostname: mariadb-backup.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - mariadb.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}-backup.${SIMVA_INTERNAL_DOMAIN:-internal.test}

# XXX: Explore options to protect /admin
# see: https://www.keycloak.org/docs/latest/server_admin/#admin-endpoints-and-console
# XXX Improve healthcheck
# see: https://issues.redhat.com/browse/KEYCLOAK-1578, https://github.com/thomasdarimont/keycloak-health-checks/
  keycloak:
    << : *default-opts
    image: ${SIMVA_KEYCLOAK_IMAGE:-quay.io/keycloak/keycloak}:${SIMVA_KEYCLOAK_VERSION:-23.0.7}
    entrypoint:
      - '/bin/bash'
      - '-c'
#      - 'su apt-get -y update && su apt-get install -y wget'
#      - '/container-tools/wait-for-it.sh -h $${KC_DB_URL_HOST} -p 3306 -t $${WAIT_TIMEOUT} -- /opt/keycloak/bin/kc.sh start-dev --import-realm'
      - '/container-tools/wait-for-it.sh -h $${KC_DB_URL_HOST} -p 3306 -t $${WAIT_TIMEOUT} -- /opt/keycloak/bin/kc.sh build && /opt/keycloak/bin/kc.sh start --optimized --import-realm'
    environment:
      # Hostname
      - KC_HOSTNAME=${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_EXTERNAL_DOMAIN:-external.test}
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_STRICT=false
      # HTTP
      - KC_HTTP_ENABLED=true
      - KC_HTTP_HOST=0.0.0.0
      - HTTP_ADDRESS_FORWARDING=true
      # PROXY
      - KC_PROXY=edge
      - PROXY_ADDRESS_FORWARDING=true
      # Health and metrics
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      # Log level
      - KC_LOG_LEVEL=${SIMVA_SSO_LOG_LEVEL:-info}
      # Database
      - KC_DB=mariadb
      - KC_DB_URL_HOST=mariadb.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      - KC_DB_URL_DATABASE=${SIMVA_KEYCLOAK_MYSQL_DATABASE:-keycloak}
      - KC_DB_USER=${SIMVA_KEYCLOAK_MYSQL_USER:-keycloak}
      - KC_DB_PASSWORD=${SIMVA_KEYCLOAK_MYSQL_PASSWORD:-password}
      # Wait Timeout for DB
      - WAIT_TIMEOUT=${SIMVA_WAIT_TIMEOUT:-240}
      # Master Realm + Admin user
      - KC_REALM_NAME=master
      - KEYCLOAK_ADMIN=${SIMVA_KEYCLOAK_ADMIN_USER:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${SIMVA_KEYCLOAK_ADMIN_PASSWORD:-password}
      #SIMVA Realm file
      - KC_FILE=/opt/keycloak/data/import/simva-realm-full.json
      - KC_SPI_THEME_DEFAULT=simva
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/keycloak/deployments:/opt/keycloak/providers
      - ${SIMVA_CONFIG_HOME:-/home/vagrant/docker-stacks/config}/keycloak/themes:/opt/keycloak/themes
      - ${SIMVA_CONTAINER_TOOLS_HOME:-/home/vagrant/docker-stacks/container-tools}:/container-tools
      - ${SIMVA_CONFIG_HOME:-/home/vagrant/docker-stacks/config}/keycloak/simva-realm/:/opt/keycloak/data/import/:ro
      - ${SIMVA_DATA_HOME}/keycloak/kcadm/:/opt/keycloak/bin/client/
    restart: unless-stopped
#    healthcheck:
#     test: "wget http://${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}:8080 || exit 1"
#     interval: 60s
#      timeout: 20s
#      retries: 3
    hostname: ${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - ${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - ${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak.rule=Host(`${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.keycloak.middlewares=secHeaders@file"

  mail:
    << : *default-opts
    image: maildev/maildev:1.1.0
    environment:
      - MAILDEV_SMTP_PORT=25
      - MAILDEV_WEB_PORT=80
    restart: unless-stopped
    healthcheck:
      test: "wget --quiet --tries=1 --spider http://localhost:80/ || exit 1"
      interval: 60s
      timeout: 20s
      retries: 3
    hostname: ${SIMVA_MAIL_HOST_SUBDOMAIN:-mail}.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - "${SIMVA_MAIL_HOST_SUBDOMAIN:-mail}.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
