version: '3.7'

volumes:
  mariadb:
    driver: local

networks:
  traefik_services:
    external: true

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.4
    environment:
      PMA_HOST: "mariadb.limesurvey.internal.test"
    depends_on:
      - mariadb
    hostname: phpmyadmin.internal.test
    networks:
      default:
        aliases:
          - phpmyadmin.limesurvey.internal.test
      traefik_services:
        aliases:
          - phpmyadmin.limesurvey.internal.test
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ls-phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.ls-phpmyadmin.rule=Host(`phpmyadmin-ls.${DOMAIN_SUFFIX:-external.test}`)"
      - "traefik.http.routers.ls-phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.ls-phpmyadmin.tls=true"  
