version: '3.7'

volumes:
  mariadb:
    driver: local

networks:
  traefik_services:
    external: true

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      PMA_HOST: "mariadb.limesurvey.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
    depends_on:
      - mariadb
    hostname: phpmyadmin.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - phpmyadmin.limesurvey.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - phpmyadmin.limesurvey.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ls-phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.ls-phpmyadmin.rule=Host(`phpmyadmin-ls.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.ls-phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.ls-phpmyadmin.tls=true"  
