version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  traefik_services:
    name: "${SIMVA_SERVICE_NETWORK:-traefik_services}"
    external: true

services:
  dozzle:
    << : *default-opts
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    hostname: logs.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    environment:
      DOZZLE_USERNAME: simva
      DOZZLE_PASSWORD: l0gg1ng
      DOZZLE_KEY: s3cr3ts1mv4
    networks:
      default:
        aliases:
          - logs.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - logs.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.logs.loadbalancer.server.port=8080"
      - "traefik.http.routers.logs.rule=Host(`logs.simva.e-ucm.es`)"
      - "traefik.http.routers.logs.middlewares=dashboardAuth@file"
