version: '3.7'

services:
  mongodb:
    image: mongo:4.2.8
    networks:
      traefik_services:
        aliases:
          - simva-mongo.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.services.simva-mongodb.loadbalancer.server.port=27017"
      - "traefik.tcp.routers.simva-mongodb.rule=HostSNI(`simva-mongo.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"
