version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  traefik_services:
    name: "${SIMVA_SERVICE_NETWORK:-traefik_services}"
    external: true
  kafka_services:
    driver: bridge
    name: "${SIMVA_KAFKA_NETWORK:-kafka_services}"
    external: true

services:
  mongodb:
    << : *default-opts
    image: mongo:4.2.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/simva/mongo:/data/db
    hostname: simva-mongo.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - simva-mongo.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    ports:
        - "27017:27017"

  simva-api:
    << : *default-opts
    image: node:14
    command: bash -c "mkdir -p /storage && cd /app && chmod +x docker-startup.sh && ./docker-startup.sh"
    stdin_open: true
    tty: true
    environment:
      DEBUG: "${SIMVA_DEBUG:-true}"
      NODE_ENV: "${SIMVA_ENVIRONMENT:-development}"
      NODE_EXTRA_CA_CERTS: "/var/lib/simva/ca/rootCA.pem"
      EXTERNAL_URL: "https://${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      PORT: "3000"
      ADMIN_USERNAME: "${SIMVA_API_ADMIN_USERNAME:-admin}"
      ADMIN_EMAIL: "${SIMVA_API_ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${SIMVA_API_ADMIN_PASSWORD:-password}"
      MAX_UPLOAD_FILE_SIZE: "${SIMVA_MAX_UPLOAD_FILE_SIZE:-33554432}"
      MONGO_HOST: "simva-mongo.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
      MONGO_DB: "/simva"
      KAFKA_HOST: "kafka1.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
      KAFKA_PORT: "9092"
      KAFKA_TOPIC: "${SIMVA_TRACES_TOPIC:-traces}"
      MINIO_URL: "https://minio.${SIMVA_EXTERNAL_DOMAIN:-external.test}/"
      MINIO_BUCKET: "${SIMVA_TRACES_BUCKET_NAME:-traces}"
      MINIO_TOPICS_DIR: "${SIMVA_SINK_TOPICS_DIR:-kafka-topics}"
      MINIO_USERS_DIR: "${SIMVA_SINK_USERS_DIR:-users}"
      MINIO_TRACES_FILE: "${SIMVA_SINK_TRACES_FILE:-traces.json}"
      LIMESURVEY_PROTOCOL: "https"
      LIMESURVEY_HOST: "limesurvey.${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      LIMESURVEY_PORT: "443"
      LIMESURVEY_EXTERNAL: "https://limesurvey.${SIMVA_EXTERNAL_DOMAIN:-external.test}/"
      LIMESURVEY_ADMIN_USER: "${SIMVA_LIMESURVEY_ADMIN_USER:-admin}"
      LIMESURVEY_ADMIN_PASSWORD: "${SIMVA_LIMESURVEY_ADMIN_PASSWORD:-password2}"
      SSO_ENABLED: "${SIMVA_SSO_ENABLED:-true}"
      SSO_REALM: "${SIMVA_SSO_REALM:-simva}"
      SSO_CLIENT_ID: "${SIMVA_FRONT_SSO_CLIENT_ID:-simva}"
      SSO_CLIENT_SECRET: "${SIMVA_FRONT_SSO_CLIENT_KEY:-secret}"
      SSO_SSL_REQUIRED: "${SSO_SSL_REQUIRED:-external}"
      SSO_PUBLIC_CLIENT: "${SSO_PUBLIC_CLIENT:-false}"
      SSO_HOST: "sso.${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      SSO_PROTOCOL: "${SIMVA_SSO_PROTOCOL:-https}"
      SSO_PORT: "${SIMVA_SSO_PORT:-443}"
      SSO_AUTH_PATH: "${SIMVA_SSO_AUTH_PATH:-/auth}"
      SSO_ADMIN_USER: "${SIMVA_SSO_ADMIN_USER:-administrator}"
      SSO_ADMIN_PASSWORD: "${SIMVA_SSO_ADMIN_PASSWORD:-administrator}"
      SIMVA_STORAGE_PATH: "/storage/"
      A2_HOST: "${SIMAV_A2_HOST:-a2}"
      A2_PORT: "${SIMVA_A2_PORT:-3000}"
      A2_PROTOCOL: "${SIMVA_A2_PROTOCOL:-http}"
      A2_ADMIN_USER: "${SIMVA_A2_ADMIN_USER:-root}"
      A2_ADMIN_PASSWORD: "${SIMVA_A2_ADMIN_PASSWORD:-password}"
      A2_EXTERNAL: "${SIMVA_A2_EXTERNAL:-https://analytics.simva.e-ucm.es}"
      LTI_PLATFORM_SIGNING_KEY: "${SIMVA_LTI_PLATFORM_SIGNING_KEY:-LTISIGNINGKEY}"
      LTI_PLATFORM_DB_NAME: "${SIMVA_LTI_PLATFORM_DB_NAME:-/lti}"
      LTI_PLATFORM_DB_USER:  "${SIMVA_LTI_PLATFORM_DB_USER:-root}"
      LTI_PLATFORM_DB_PASSWORD: "${SIMVA_LTI_PLATFORM_DB_PASSWORD:-password}"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SIMVA_TLS_HOME?TLS home folder required}/ca:/var/lib/simva/ca
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/simva/simva-api:/app
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/simva/storage:/storage
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/simva/simva-api-logs:/root/.npm/_logs/
    depends_on:
      - mongodb
    hostname: simva-api.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - simva-api.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - simva-api.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      kafka_services:
        aliases:
          - simva-api.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.simva-api.loadbalancer.server.port=3000"
      - "traefik.http.routers.simva-api.rule=Host(`simva-api.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"

  simva-front:
    << : *default-opts
    image: node:12.18.2
    command: bash -c "cd /app && chmod +x docker-startup.sh && ./docker-startup.sh"
    stdin_open: true
    tty: true
    environment:
      DEBUG: "${SIMVA_DEBUG:-true}"
      NODE_ENV: "${SIMVA_ENVIRONMENT:-development}"
      NODE_EXTRA_CA_CERTS: "/var/lib/simva/ca/rootCA.pem"
      SIMVA_HOST:  "simva-api.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
      SIMVA_PORT: "3000"
      SIMVA_PROTOCOL: "http"
      SIMVA_URL: "https://${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      MONGO_HOST: "simva-mongo.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
      MONGO_DB: "/simva-front"
      SSO_HOST: "sso.${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      SSO_PROTOCOL: "${SIMVA_SSO_PROTOCOL:-https}"
      SSO_PORT: "${SIMVA_SSO_PORT:-443}"
      SSO_AUTH_PATH: "${SIMVA_SSO_AUTH_PATH:-/auth}"
      SSO_REALM: "${SIMVA_SSO_REALM:-simva}"
      SSO_CLIENT_ID: "${SIMVA_FRONT_SSO_CLIENT_ID:-simva}"
      SSO_CLIENT_SECRET: "${SIMVA_FRONT_SSO_CLIENT_KEY:-secret}"
      SSO_SSL_REQUIRED: "${SSO_SSL_REQUIRED:-external}"
      SSO_PUBLIC_CLIENT: "${SSO_PUBLIC_CLIENT:-false}"
      SIMVA_API_HOST: "simva-api.${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      SIMVA_API_PORT: "443"
      SIMVA_API_PROTOCOL: "https"
      LIMESURVEY_HOST: "https://limesurvey.${SIMVA_EXTERNAL_DOMAIN:-external.test}/"
      LIMESURVEY_PROTOCOL: "https"
      LIMESURVEY_PORT: "443"
      LIMESURVEY_ADMIN_USER: "${SIMVA_LIMESURVEY_ADMIN_USER:-admin}"
      LIMESURVEY_ADMIN_PASSWORD: "${SIMVA_LIMESURVEY_ADMIN_PASSWORD:-password2}"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SIMVA_TLS_HOME?TLS home folder required}/ca:/var/lib/simva/ca
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/simva/simva-front:/app
    depends_on:
      - simva-api
    hostname: simva-front.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - simva-front.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - simva-front.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.simva-front.loadbalancer.server.port=3050"
      - "traefik.http.routers.simva-front.rule=Host(`${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"

  simva-trace-allocator:
    << : *default-opts
    image: node:20.9.0-bullseye
    command: bash -c "cd /app && chmod +x docker-startup.sh && ./docker-startup.sh"
    stdin_open: true
    tty: true
    environment:
      DEBUG: "${SIMVA_DEBUG:-true}"
      TRY_RECOVERY: "true"
      REMOVE_DRY_RUN: "false"
      LOG_LEVEL: "debug"
      BATCH_SIZE: "${SIMVA_TRACE_ALLOCATOR_BATCH_SIZE:-100}"
      REFRESH_INTERVAL: "${SIMVA_TRACE_ALLOCATOR_REFRESH_INTERVAL:-14400000}"
      NODE_ENV: "${SIMVA_ENVIRONMENT:-development}"
      NODE_EXTRA_CA_CERTS: "/var/lib/simva/ca/rootCA.pem"
      SIMVA_HOST: "simva-api.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
      SIMVA_PORT: "3000"
      SIMVA_PROTOCOL: "http"
      SIMVA_USER: "${SIMVA_API_ADMIN_USERNAME}"
      SIMVA_EMAIL: "${SIMVA_API_ADMIN_EMAIL}"
      SIMVA_PASSWORD: "${SIMVA_API_ADMIN_PASSWORD}"
      LOCAL_STATE: "/data"
      MINIO_BUCKET: ${SIMVA_TRACES_BUCKET_NAME:-traces}
      MINIO_HOST: "minio.${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      MINIO_SSL: "true"
      MINIO_ACCESS_KEY: "${SIMVA_MINIO_ACCESS_KEY:-root}"
      MINIO_SECRET_KEY: "${SIMVA_MINIO_SECRET_KEY:-password}"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SIMVA_TLS_HOME?TLS home folder required}/ca:/var/lib/simva/ca
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/simva/simva-trace-allocator:/app
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/simva/simva-trace-allocator-data:/data
    depends_on:
      - simva-api
    hostname: simva-trace-allocator.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - simva-trace-allocator.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - simva-trace-allocator.${SIMVA_INTERNAL_DOMAIN:-internal.test}
